# Generated by Django 2.2.16 on 2022-04-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220414_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите картинку', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
